version: "3.8"

secrets:
  APP_PASSWORD:
    external: true
  APP_USER:
    external: true
  JWT_ACCESS_EXPIRE_TIME:
    external: true
  JWT_REFRESH_EXPIRE_TIME:
    external: true
  JWT_SECRET:
    external: true
  MONGODB_URI:
    external: true
  PORT:
    external: true

services:
  backend:
    image: platyna100/wallet-backend:figma
    secrets:
      - APP_PASSWORD
      - APP_USER
      - JWT_ACCESS_EXPIRE_TIME
      - JWT_REFRESH_EXPIRE_TIME
      - JWT_SECRET
      - MONGODB_URI
      - PORT
  frontend:
    image: platyna100/wallet-frontend:new
  frontend_figma:
    image: platyna100/wallet-frontend:figma
  nginx:
    image: platyna100/wallet-nginx:figma
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/ssl/uwallet.pl/:/etc/nginx/ssl/uwallet.pl/
      - /etc/letsencrypt/ssl/figma.uwallet.pl/:/etc/nginx/ssl/figma.uwallet.pl/
